name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # versión de Python

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: |
          export FLASK_APP=app.py  # Configurar la variable de entorno FLASK_APP
          gunicorn app:app --bind 0.0.0.0:5000 &  # Ejecutar la aplicación con Gunicorn
          sleep 10  # Esperar unos segundos para que la aplicación se inicie
          echo "La aplicación Flask está disponible en: http://$(curl --silent ifconfig.me):5000"
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.8.17/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.17/x64/lib
      - name: Limpiar procesos orfanos
        run: |
          sleep 120  # Esperar un minuto antes de limpiar los procesos orfanos
          ps aux | grep '[g]unicorn' | awk '{print $2}' | xargs kill -9
